import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { saveEmployeeCorrectionAction, saveUserAccountAction } from "@/app/actions/employees";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { DivergenceList, divergenceLabels } from "@/components/divergence-list";
import { ClockIcon, ProjectsIcon, UsersIcon, WarningIcon } from "@/components/icons";
import { defaultPunchPeriod, getEmployeeDetail } from "@/lib/dal";
import { cleanLabel, formatDate, formatMinutes, roleLine } from "@/lib/format";

export const metadata: Metadata = { title: "Detalhes do colaborador" };

function maskCpf(cpf: string | null) {
  return cpf ? `***.***.${cpf.slice(6, 9)}-${cpf.slice(9)}` : "Não vinculado";
}

const dimepIssueLabel: Record<string, string> = {
  unmatched_employee: "Pessoa sem vínculo", invalid_punch: "Batida inválida", missing_end: "Batida de saída ausente",
  duplicate_time: "Batida duplicada", cross_midnight: "Jornada atravessa meia-noite", other: "Revisão necessária",
};

export default async function EmployeeDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ correction?: string; account?: string; de?: string; ate?: string }> }) {
  const { id } = await params;
  const feedback = await searchParams;
  const isDate = (value?: string) => Boolean(value && /^\d{4}-\d{2}-\d{2}$/.test(value));
  const fallback = defaultPunchPeriod();
  // Um dia só é um período com início e fim iguais; a tela aceita as duas formas.
  const period = {
    from: isDate(feedback.de) ? feedback.de! : fallback.from,
    to: isDate(feedback.ate) ? feedback.ate! : isDate(feedback.de) ? feedback.de! : fallback.to,
  };
  const detail = await getEmployeeDetail(id, period.from <= period.to ? period : { from: period.to, to: period.from });
  if (!detail) notFound();
  const correction = feedback.correction;
  const canCorrect = detail.session.roles.some((role) => ["hr", "director", "admin"].includes(role));
  const employee = detail.employee;
  return <div className="page-container wide-page">
    <Breadcrumbs items={[{ label: "Visão geral", href: "/" }, { label: "Colaboradores", href: "/employees" }, { label: employee.name }]} />
    <header className="page-header"><div><span className="eyebrow">COLABORADOR</span><h1>{employee.name}</h1><p>{roleLine(employee.job_title, employee.department)}</p></div><span className={`status-badge ${employee.employment_status === "active" ? "status-success" : "status-neutral"}`}>{employee.employment_status === "active" ? "Ativo" : employee.employment_status}</span></header>
    {correction === "ok" && <div className="success-banner">Correção local salva com trilha de auditoria.</div>}
    {correction === "invalid" && <div className="form-error">Revise os campos e informe um motivo com pelo menos 10 caracteres.</div>}
    {correction === "empty" && <div className="form-error">Informe pelo menos um campo para sobrepor.</div>}
    {feedback.account === "ok" && <div className="success-banner">Conta de acesso atualizada com trilha de auditoria.</div>}
    {feedback.account === "invalid" && <div className="form-error">Revise nome, e-mail, telefone em formato internacional e motivo da alteração.</div>}
    <section className="detail-summary"><article><ProjectsIcon /><span><small>Projetos vinculados</small><strong>{detail.projects.length}</strong></span></article><article><ClockIcon /><span><small>Apontamentos</small><strong>{detail.workHistory.length}</strong></span></article><article><WarningIcon /><span><small>Divergências pendentes</small><strong>{detail.divergences.length}</strong></span></article></section>
    <div className="employee-detail-grid">
      <section className="panel detail-box"><h2>Cadastro efetivo</h2><dl className="profile-list"><div><dt>CPF</dt><dd>{maskCpf(employee.cpf_digits)} {employee.cpf_is_valid ? "· validado" : "· não validado"}</dd></div><div><dt>Matrícula</dt><dd>{employee.employee_number || "Não informada"}</dd></div><div><dt>Nome na origem</dt><dd>{employee.source_name}</dd></div><div><dt>Função</dt><dd>{employee.job_title || "Não informada"}</dd></div><div><dt>Departamento</dt><dd>{employee.department || "Não informado"}</dd></div><div><dt>E-mail</dt><dd>{employee.email || "Não informado"}</dd></div><div><dt>Telefone</dt><dd>{employee.phone || "Não informado"}</dd></div></dl><p className="readiness-note">O CPF é chave de conciliação e não é editado aqui. Divergências de identidade devem passar pela revisão DIMEP/IMUV.</p></section>
      <section className="panel detail-box"><h2>Projetos</h2>{detail.projects.map((project) => <Link key={project.id} href={`/projects/${project.id}`} className="history-link"><span><strong>{project.code} · {project.name}</strong><small>{project.source} · {project.status}</small></span><ProjectsIcon /></Link>)}{!detail.projects.length && <p className="empty-copy">Sem projeto ativo vinculado.</p>}</section>
    </div>
    {canCorrect && <section className="panel detail-box detail-wide"><h2>Correção cadastral auditável</h2><p>Preencha somente os campos que precisam sobrepor temporariamente a origem. Antes do envio ao IMUV, Configurações mostrará cada valor atual e novo.</p><form action={saveEmployeeCorrectionAction} className="correction-form"><input type="hidden" name="collaboratorId" value={employee.id} /><div className="form-grid two-columns"><label className="field-group"><span>Nome exibido</span><input className="input-field" name="fullName" defaultValue={employee.full_name_override || ""} placeholder={employee.source_name} /></label><label className="field-group"><span>Matrícula</span><input className="input-field" value={employee.source_employee_number || "Não informada"} readOnly disabled /><small className="field-help">A matrícula é a chave de conciliação com o DIMEP e não pode ser alterada aqui. Cadastros repetidos aparecem como alerta de duplicidade em Colaboradores.</small></label><label className="field-group"><span>Função exibida</span><input className="input-field" name="jobTitle" defaultValue={employee.job_title_override || ""} placeholder={cleanLabel(employee.source_job_title) || "Não informada"} /></label><label className="field-group"><span>Departamento exibido</span><input className="input-field" name="department" defaultValue={employee.department_override || ""} placeholder={cleanLabel(employee.source_department) || "Não informado"} /></label><label className="field-group"><span>E-mail</span><input className="input-field" type="email" name="email" defaultValue={employee.email_override || ""} placeholder={employee.source_email || "nome@empresa.com.br"} /></label><label className="field-group"><span>Telefone</span><input className="input-field" name="phone" defaultValue={employee.phone_override || ""} placeholder={employee.source_phone || "Não informado"} /></label><label className="field-group"><span>Situação</span><select className="input-field" name="activeOverride" defaultValue={employee.active_override === null ? "" : String(employee.active_override)}><option value="">Manter origem ({employee.source_active ? "Ativo" : "Inativo"})</option><option value="true">Ativo</option><option value="false">Inativo</option></select></label></div><label className="field-group"><span>Motivo da correção <b>*</b></span><textarea className="input-field" name="reason" rows={2} minLength={10} maxLength={1000} defaultValue={employee.override_reason || ""} required /></label>{employee.override_updated_at && <label className="check-row danger-zone"><input type="checkbox" name="removeOverride" /><span>Remover todas as correções locais e voltar aos dados sincronizados</span></label>}<button className="button button-primary" type="submit">Salvar correção local</button></form></section>}
    {canCorrect && detail.account && <section className="panel detail-box detail-wide"><h2>Conta de acesso ao RDO</h2><p>Dados de autenticação pertencem ao aplicativo RDO e não são enviados ao IMUV.</p><form action={saveUserAccountAction} className="correction-form"><input type="hidden" name="collaboratorId" value={employee.id} /><input type="hidden" name="userId" value={detail.account.user_id} /><div className="form-grid two-columns"><label className="field-group"><span>Nome da conta</span><input className="input-field" name="displayName" defaultValue={detail.account.display_name} required /></label><label className="field-group"><span>E-mail de acesso</span><input className="input-field" type="email" name="accountEmail" defaultValue={detail.account.email || ""} required /></label><label className="field-group"><span>Telefone internacional</span><input className="input-field" name="phoneE164" defaultValue={detail.account.phone_e164 || ""} placeholder="+5511999999999" /></label><label className="check-row"><input type="checkbox" name="accountActive" defaultChecked={detail.account.active} /><span>Conta ativa · perfis: {detail.account.roles.join(", ")}</span></label></div><label className="field-group"><span>Motivo da alteração <b>*</b></span><textarea className="input-field" name="accountReason" minLength={10} maxLength={1000} required rows={2} /></label><button className="button button-secondary" type="submit">Salvar conta de acesso</button></form></section>}
    <section className="panel detail-box detail-wide"><h2>Colaboração e horários</h2><div className="history-table"><div className="history-row history-head"><span>Data</span><span>Projeto / tarefa</span><span>Intervalo</span><span>Conciliação</span></div>{detail.workHistory.map((item, index) => <Link href={`/rdos/${item.rdo_id}`} className="history-row" key={`${item.rdo_id}-${index}`}><span>{formatDate(item.work_date)}</span><span><strong>{item.project_code} · {item.project_name}</strong><small>{item.task_code} · {item.task_name}</small></span><span>{new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit", timeZone: "America/Sao_Paulo" }).format(item.starts_at)}–{new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit", timeZone: "America/Sao_Paulo" }).format(item.ends_at)}</span><span className={item.divergence_status === "pending" ? "danger-text" : ""}>{item.divergence_type ? `${divergenceLabels[item.divergence_type] || item.divergence_type} · ${item.divergence_status === "accepted" ? "aceita" : item.divergence_status === "rejected" ? "correção solicitada" : "pendente"}` : "Sem divergência"}</span></Link>)}{!detail.workHistory.length && <p className="empty-copy">Nenhuma participação em RDO registrada.</p>}</div></section>
    <section className="panel detail-box detail-wide"><h2>Jornada registrada no relógio de ponto</h2><form className="punch-filter" action={`/employees/${employee.id}`}><label className="field-group"><span>De</span><input className="input-field" type="date" name="de" defaultValue={detail.period.from} max={detail.period.to} /></label><label className="field-group"><span>Até</span><input className="input-field" type="date" name="ate" defaultValue={detail.period.to} /></label><button className="button button-secondary" type="submit">Filtrar</button><Link className="text-button" href={`/employees/${employee.id}`}>Últimos 30 dias</Link></form><p className="readiness-note">Batidas como o DIMEP entregou, comparadas com o tempo já distribuído em RDO no mesmo dia. Informe apenas a data inicial para ver um único dia.</p><div className="history-table"><div className="history-row history-head punch-row"><span>Data</span><span>Intervalos</span><span>Jornada</span><span>Distribuído em RDO</span><span>Situação</span></div>{detail.punches.map((item) => { const allocated = item.allocated_minutes ?? 0; const pending = Number(item.open_issues) > 0; return <div className="history-row punch-row" key={item.work_date}><span>{formatDate(item.work_date)}</span><span><strong>{item.interval_label}</strong><small>{item.segment_count} segmento(s)</small></span><span>{formatMinutes(item.total_minutes)}</span><span>{allocated ? formatMinutes(allocated) : "—"}</span><span className={pending ? "danger-text" : ""}>{pending ? `${item.open_issues} pendência(s) do ponto` : allocated >= item.total_minutes ? "Coberto por RDO" : allocated ? "Parcialmente distribuído" : "Aguardando RDO"}</span></div>; })}{!detail.punches.length && <p className="empty-copy">Nenhuma batida importada entre {formatDate(detail.period.from)} e {formatDate(detail.period.to)}.</p>}</div></section>
    <section className="panel detail-box detail-wide"><h2>Divergências a tratar</h2><p className="readiness-note">Aceite a justificativa, solicite correção ao líder ou dispense a ocorrência do relógio de ponto. Toda decisão fica registrada na trilha de auditoria.</p><DivergenceList divergences={detail.divergences} showDate /></section>
    {detail.dimepIssues.length > 0 && <section className="panel detail-box detail-wide"><h2>Pendências do relógio de ponto</h2><p className="readiness-note">Geradas automaticamente durante a importação DIMEP e mantidas separadas das justificativas de RDO.</p>{detail.dimepIssues.map((item) => <div className="event-row" key={item.id}><WarningIcon /><span><strong>{item.work_date ? formatDate(item.work_date) : "Data inválida"} · {dimepIssueLabel[item.issue_type] || item.issue_type}</strong><small>Detectado na sincronização de {new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(item.first_seen_at)}</small></span></div>)}</section>}
    {(detail.occurrences.length > 0 || detail.quality.length > 0) && <section className="panel detail-box detail-wide"><h2>Ocorrências e qualidade nos RDOs em que participou</h2><p className="readiness-note">Estes registros pertencem ao RDO da equipe; não atribuem responsabilidade individual automaticamente.</p>{detail.occurrences.map((item) => <Link href={`/rdos/${item.rdo_id}`} className="event-row" key={item.id}><WarningIcon /><span><strong>{formatDate(item.work_date)} · {item.project_name} · {item.severity}</strong><small>{item.description} · {item.status}</small></span></Link>)}{detail.quality.map((item) => <Link href={`/rdos/${item.rdo_id}`} className="event-row" key={item.id}><UsersIcon /><span><strong>{formatDate(item.work_date)} · {item.project_name} · {item.record_type}</strong><small>{item.description} · {item.result}</small></span></Link>)}</section>}
  </div>;
}
